
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class shopping1 extends javax.swing.JFrame {

    /**
     * Creates new form shopping1
     */
    public shopping1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TEXT1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        VISA = new javax.swing.JRadioButton();
        XYZ = new javax.swing.JRadioButton();
        ABC = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        TEXT2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TEXT3 = new javax.swing.JTextField();
        clearALL = new javax.swing.JButton();
        BT2 = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("  SHOPPING MALL DISCUONT CALCULATOR");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("  SHOPPING AMOUNT");

        TEXT1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        TEXT1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TEXT1KeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("CARD TYPE");

        buttonGroup1.add(VISA);
        VISA.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        VISA.setText("VISA");
        VISA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VISAActionPerformed(evt);
            }
        });

        buttonGroup1.add(XYZ);
        XYZ.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        XYZ.setText("XYZ");
        XYZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XYZActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(VISA, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(XYZ, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(VISA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(XYZ, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        buttonGroup1.add(ABC);
        ABC.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        ABC.setText("ABC");
        ABC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABCActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Discount AMOUNT");

        TEXT2.setEditable(false);
        TEXT2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        TEXT2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TEXT2KeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("NET PRICE");

        TEXT3.setEditable(false);
        TEXT3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        TEXT3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TEXT3KeyTyped(evt);
            }
        });

        clearALL.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        clearALL.setText("clearALL");
        clearALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearALLActionPerformed(evt);
            }
        });

        BT2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BT2.setText("CALCULATE NET PRICE");
        BT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT2ActionPerformed(evt);
            }
        });

        EXIT.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TEXT1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(213, 213, 213))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ABC, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(198, 198, 198))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clearALL, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(BT2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TEXT2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(155, 155, 155)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TEXT3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEXT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ABC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TEXT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(TEXT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearALL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
            JFrame fream=new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog(fream, "Thank You for shopping","EXIT",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
            
           
        }
        
    }//GEN-LAST:event_EXITActionPerformed

    private void clearALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearALLActionPerformed
        // clearALL
        TEXT1.setText("");
        TEXT2.setText("");
        TEXT3.setText("");
        VISA.setSelected(false);
        XYZ.setSelected(false);
        ABC.setSelected(false);
    }//GEN-LAST:event_clearALLActionPerformed

    private void TEXT1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
if (!(Character.isDigit(c))||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE) {
evt.consume();

}
    }//GEN-LAST:event_TEXT1KeyTyped

    private void TEXT2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT2KeyTyped
        // TODO add your handling code here:
char a=evt.getKeyChar();
if(!(Character.isDigit(a))||a==KeyEvent.VK_BACK_SPACE||a==KeyEvent.VK_DELETE){
     evt.consume();
}
    }//GEN-LAST:event_TEXT2KeyTyped

    private void TEXT3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT3KeyTyped
        // TODO add your handling code here:
        char n=evt.getKeyChar();
        if(!(Character.isDigit(n))||n==KeyEvent.VK_BACK_SPACE||n==KeyEvent.VK_DELETE){
     evt.consume();
}
    }//GEN-LAST:event_TEXT3KeyTyped
 double netprice;
 double ShoppingAmotunt;
 double Discount; 
    private void BT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT2ActionPerformed
        // TODO add your handling code here:
      if(VISA.isSelected()){
   if(ShoppingAmotunt<500)
   {
       ShoppingAmotunt=Double.parseDouble(TEXT1.getText());
        Discount=ShoppingAmotunt*(0.10);
        netprice=ShoppingAmotunt - Discount;
         String tot=new Double(netprice).toString();
         String tot1=new Double(Discount).toString();
         TEXT3.setText(tot);
         TEXT2.setText(tot1);
   }
   else if(ShoppingAmotunt >=5000)
   {
        ShoppingAmotunt=Double.parseDouble(TEXT1.getText());
        Discount=ShoppingAmotunt*(0.20);
        netprice=ShoppingAmotunt - Discount;
         String tot=new Double(netprice).toString();
         String tot1=new Double(Discount).toString();
         TEXT3.setText(tot);
         TEXT2.setText(tot1);
   }
   else
   {
       Discount=0;
       netprice=ShoppingAmotunt - Discount;
         String tot=new Double(netprice).toString();
         String tot1=new Double(Discount).toString();
         TEXT3.setText(tot);
         TEXT2.setText(tot1);
   }
      } 
       if(XYZ.isSelected())
       {
             if(ShoppingAmotunt<10000)
   {
       ShoppingAmotunt=Double.parseDouble(TEXT1.getText());
        Discount=ShoppingAmotunt*(0.15);
        netprice=ShoppingAmotunt - Discount;
         String tot=new Double(netprice).toString();
         String tot1=new Double(Discount).toString();
         TEXT3.setText(tot);
         TEXT2.setText(tot1);
   }
   else if(ShoppingAmotunt >=10000)
   {
        ShoppingAmotunt=Double.parseDouble(TEXT1.getText());
        Discount=ShoppingAmotunt*(0.25);
        netprice=ShoppingAmotunt - Discount;
         String tot=new Double(netprice).toString();
         String tot1=new Double(Discount).toString();
         TEXT3.setText(tot);
         TEXT2.setText(tot1);
   }
   else
   {
       Discount=0;
       netprice=ShoppingAmotunt - Discount;
         String tot=new Double(netprice).toString();
         String tot1=new Double(Discount).toString();
         TEXT3.setText(tot);
         TEXT2.setText(tot1);
   }
       }
      if(ABC.isSelected())
      { 
                  if(ShoppingAmotunt<8000)
   {
       ShoppingAmotunt=Double.parseDouble(TEXT1.getText());
        Discount=ShoppingAmotunt*(0.12);
        netprice=ShoppingAmotunt - Discount;
         String tot=new Double(netprice).toString();
         String tot1=new Double(Discount).toString();
         TEXT3.setText(tot);
         TEXT2.setText(tot1);
   }
   else if(ShoppingAmotunt >=8000)
   {
        ShoppingAmotunt=Double.parseDouble(TEXT1.getText());
        Discount=ShoppingAmotunt*(0.15);
        netprice=ShoppingAmotunt - Discount;
         String tot=new Double(netprice).toString();
         String tot1=new Double(Discount).toString();
         TEXT3.setText(tot);
         TEXT2.setText(tot1);
   }
   else
   {
       Discount=0;
       netprice=ShoppingAmotunt - Discount;
         String tot=new Double(netprice).toString();
         String tot1=new Double(Discount).toString();
         TEXT3.setText(tot);
         TEXT2.setText(tot1);
   }
      } 
      
    }//GEN-LAST:event_BT2ActionPerformed

    private void VISAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VISAActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_VISAActionPerformed

    private void XYZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XYZActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_XYZActionPerformed

    private void ABCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABCActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ABCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shopping1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shopping1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shopping1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shopping1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shopping1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ABC;
    private javax.swing.JButton BT2;
    private javax.swing.JButton EXIT;
    private javax.swing.JTextField TEXT1;
    private javax.swing.JTextField TEXT2;
    private javax.swing.JTextField TEXT3;
    private javax.swing.JRadioButton VISA;
    private javax.swing.JRadioButton XYZ;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearALL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
